# Generated by Django 4.0.3 on 2022-06-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
                ('currency', models.CharField(choices=[('Доллар', 'Доллар'), ('Сум', 'Сум'), ('Евро', 'Евро')], default='Доллар', max_length=32, verbose_name='Валюта')),
                ('area', models.PositiveIntegerField(verbose_name='Площадь')),
                ('room_amount', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('type', models.CharField(choices=[('Участок', 'Участок недвижимости'), ('Квартира', 'Квартира')], default='Квартира', max_length=64, verbose_name='Тип недвижимости')),
            ],
        ),
    ]
