# Generated by Django 4.0.3 on 2022-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Категории')),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='categories',
            field=models.ManyToManyField(related_name='estates', to='main.category'),
        ),
    ]
