# Generated by Django 4.0.3 on 2022-06-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_estate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
