# Generated by Django 4.0.3 on 2022-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_estate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
