# Generated by Django 4.0.3 on 2022-06-25 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_estate_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='estate',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
