# Generated by Django 4.0.3 on 2022-06-28 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_estate_created_at_remove_estate_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.estate')),
            ],
        ),
    ]
